name: Dependabot automerge

on:
    - workflow_call

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: write
    pull-requests: write

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        steps:
        - uses: ./.github/workflows/dependabot-automerge/action.yml
          with:
              github-token: ${{secrets.YARD_BOT_PAT}}
